### ISSUE TITLE
[Deployment] Deploy project as vs code extension

### ISSUE THREAD

**Issue by fliklab** [YouOnlyCopyOnce/YOCO#5]
# FEATURE

## Summary

> 이슈 요약

VS Code Marketplace 배포를 위한 설정을 진행하고 배포합니다.

## To-Do

- [ ] 배포 설정 파일 작성 및 패키징
- [ ] 로컬 환경에서 테스트
- [ ] VS Code Marketplace 계정 생성
- [ ] Extension 배포

## ETC

> 기타 사항

**Comment by givvemee** [comment]
resolved in #13
